### PR TITLE
Added an SVS tile source

### PR DESCRIPTION
**Pull request by manthey**
Since we read out of the SVS file and then serve tiles by reencoding them.  You can ask for PNGs by adding ?encoding=PNG to the GET item/{id}/tiles/zxy or GET item/{id}/tiles queries. Similarly, you can set the jpeg quality and subsampling with ?jpegQuality=(quality)&jpegSubsampling=subsampling on those queries.

There is test coverage, but it may take some iterations to get it fully working on Travis.  The known issue of OpenJPEG with Ubuntu 14.04 applies.

### CODE REVIEW

**Comment by brianhelba** [comment]
Since the SVS image is coming from a public source, I'd like to maintain some limited provenance (though you could always look up the file on ``midas3.kitware.com``, I suppose). Can you move `` plugin_tests/test_keys/sample_svs_image.svs.md5 `` -> `` plugin_tests/test_keys/sample_svs_images/TCGA-DU-6399-01A-01-TS1.e8eb65de-d63e-42db-af6f-14fefbbdf7bd.svs.md5``

**Comment by manthey** [comment]
No problem.

**Comment by manthey** [comment]
@brianhelba I've finally gotten travis to test this successfully.

**Comment by brianhelba** [comment]
LGTM.

**Pull request merged**
