### PR TITLE
Small image support

### PR DESCRIPTION
**Pull request by manthey**
Allow small images to be used as single tiles.

When used as a Girder plugin, the maximum size that is allowed is stored in a setting (a value of 0 disables direct use of small images).  When used without Girder, the maximum size is specified in server/tilesource/pil.py.  In either case, it can be overridden when asking for a tile source with the maxSize parameter.

This also includes an update to the geojs viewer to better handle images with massive tiles.  It will also properly crop edges when we update the geojs version.

### CODE REVIEW

**Comment by manthey** [comment]
This resolves issue #84.

**Comment by manthey** [comment]
@cdeepakroy This still needs some tests, but otherwise is fully functional.  Currently, the limit for using a single image is set to 4096x4096 pixels.

**Comment by manthey** [comment]
@cdeepakroy This PR should be ready for testing.

**Comment by cdeepakroy** [comment]
LGTM! I just tested it and it works!

**Pull request merged**
