### PR TITLE
Girder worker

### PR DESCRIPTION
**Pull request by manthey**
Use girder_worker instead of Romanesco.

This is currently dependent on the python tests branch; it could be separated, but since that branch is ready to go, I'd rather see that branch merged and this one's history cleaned up.

### CODE REVIEW

**Comment by brianhelba** [comment]
LGTM. I see no reason to rebase this, the history should end up fine.

**Comment by brianhelba** [comment]
Nevermind, it is failing to merge. I'll rebase now.

**Comment by manthey** [comment]
I just merged it after your comment -- I think I just beat you to it, that is all.

**Comment by brianhelba** [comment]
Yup, all set here.

**Pull request merged**
